### ISSUE TITLE
Stuck with 0.6b lm.

### ISSUE THREAD

**Issue by p3trich0rX** [scragnog/ACE-Step-1.5-for-windows#1]
**Here are my terminal output:**

> Uninstalled 1 package in 30ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                                                         warning: Failed to symlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, symlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 629ms
W0221 20:22:47.644000 13052 .venv\Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
2026-02-21 20:22:49.570 | WARNING  | acestep.training.trainer:<module>:36 - bitsandbytes not installed. Using standard AdamW.
INFO:     Started server process [13052]
INFO:     Waiting for application startup.
2026-02-21 20:22:51.757 | INFO     | acestep.gpu_config:get_gpu_memory_gb:390 - CUDA GPU detected: NVIDIA GeForce RTX 5060 Ti (15.9 GB)
2026-02-21 20:22:51.757 | INFO     | acestep.gpu_config:get_gpu_tier:548 - Detected 15.93GB VRAM — treating as 16GB class GPU

============================================================
[API Server] GPU Configuration Detected:
============================================================
  GPU Memory: 15.93 GB
  Configuration Tier: tier6a
  Max Duration (with LM): 480s
  Max Duration (without LM): 600s
  Max Batch Size (with LM): 4
  Max Batch Size (without LM): 8
  Default LM Init: True
  Available LM Models: ['acestep-5Hz-lm-0.6B', 'acestep-5Hz-lm-1.7B']
============================================================

[API Server] Auto-enabling CPU offload (GPU < 16GB)
[API Server] Initializing models at startup...
[API Server] Auto-enabling CPU offload (GPU < 16GB)
[API Server] Auto-setting offload_to_cpu=True based on GPU memory
[Model Download] Model acestep-v15-turbo already exists at C:\Yeni klasör\ACE-Step-1.5-for-windows\checkpoints\acestep-v15-turbo
[Model Download] Model vae already exists at C:\Yeni klasör\ACE-Step-1.5-for-windows\checkpoints\vae
[API Server] Loading primary DiT model: acestep-v15-turbo
2026-02-21 20:22:51.762 | INFO     | acestep.core.generation.handler.init_service_orchestrator:_reset_lora_state:39 - [_reset_lora_state] LoRA/LoKr state cleared
2026-02-21 20:22:51.829 | INFO     | acestep.core.generation.handler.init_service_loader:_load_main_model_from_checkpoint:55 - [initialize_service] Attempting to load model with attention implementation: flash_attention_2
`torch_dtype` is deprecated! Use `dtype` instead!
2026-02-21 20:22:52.304 | INFO     | acestep.core.generation.handler.init_service_loader:_load_main_model_from_checkpoint:79 - [initialize_service] Keeping main model on cuda (persistent)
[API Server] Primary model loaded: acestep-v15-turbo
[API Server] GPU auto-detection: init_llm=True (VRAM: 15.9GB, tier: tier6a)
[API Server] ACESTEP_INIT_LLM=auto, using GPU auto-detection result
[API Server] Loading LLM model...
[API Server] Auto-selected LM model: acestep-5Hz-lm-1.7B based on GPU tier
[Model Download] Model acestep-5Hz-lm-1.7B already exists at C:\Yeni klasör\ACE-Step-1.5-for-windows\checkpoints\acestep-5Hz-lm-1.7B
2026-02-21 20:23:04.144 | INFO     | acestep.llm_inference:initialize:568 - loading 5Hz LM tokenizer... it may take 80~90s
2026-02-21 20:23:19.010 | INFO     | acestep.llm_inference:initialize:572 - 5Hz LM tokenizer loaded successfully in 14.87 seconds
2026-02-21 20:23:19.011 | INFO     | acestep.llm_inference:initialize:577 - Initializing constrained decoding processor...
2026-02-21 20:23:19.013 | INFO     | acestep.llm_inference:initialize:583 - Setting constrained decoding max_duration to 480s based on GPU config (tier: tier6a)
2026-02-21 20:23:20.004 | DEBUG    | acestep.constrained_logits_processor:_precompute_audio_code_tokens:577 - Found 1535 audio code tokens with values outside valid range [0, 63999]
2026-02-21 20:23:22.601 | INFO     | acestep.llm_inference:initialize:591 - Constrained processor initialized in 3.59 seconds
2026-02-21 20:23:22.601 | INFO     | acestep.gpu_config:get_gpu_memory_gb:390 - CUDA GPU detected: NVIDIA GeForce RTX 5060 Ti (15.9 GB)
2026-02-21 20:23:23.767 | INFO     | acestep.gpu_config:get_lm_gpu_memory_ratio:769 - [get_lm_gpu_memory_ratio] model=1.7B, free=10.31GB, current_usage=5.62GB, lm_target=4.70GB, usable_for_lm=4.70GB, ratio=0.648
2026-02-21 20:23:23.768 | INFO     | acestep.llm_inference:get_gpu_memory_utilization:183 - Adaptive LM memory allocation: model=C:\Yeni klasör\ACE-Step-1.5-for-windows\checkpoints\acestep-5Hz-lm-1.7B, target=3.4GB, ratio=0.648, total_gpu=15.9GB
2026-02-21 20:23:23.770 | INFO     | acestep.llm_inference:_initialize_5hz_lm_vllm:717 - Initializing 5Hz LM with model: C:\Yeni klasör\ACE-Step-1.5-for-windows\checkpoints\acestep-5Hz-lm-1.7B, enforce_eager: False, tensor_parallel_size: 1, max_model_len: 4096, gpu_memory_utilization: 0.648
2026-02-21 20:23:30.264 | INFO     | acestep.llm_inference:initialize:659 - 5Hz LM status message: ❌ Error initializing 5Hz LM: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

Traceback:
Traceback (most recent call last):
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\acestep\llm_inference.py", line 719, in _initialize_5hz_lm_vllm
    self.llm = LLM(
               ^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\engine\llm_engine.py", line 40, in __init__
    self.model_runner = ModelRunner(config, 0, self.events)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\engine\model_runner.py", line 129, in __init__
    self.warmup_model()
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\engine\model_runner.py", line 229, in warmup_model
    self.run(seqs, True)
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\engine\model_runner.py", line 594, in run
    logits = self.run_model(input_ids, positions, is_prefill)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\engine\model_runner.py", line 423, in run_model
    out = self.model.compute_logits(self.model(input_ids, positions))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\models\qwen3.py", line 224, in forward
    return self.model(input_ids, positions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\models\qwen3.py", line 181, in forward
    hidden_states, residual = layer(positions, hidden_states, residual)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\models\qwen3.py", line 153, in forward
    hidden_states, residual = self.input_layernorm(hidden_states), hidden_states
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\nanovllm\layers\layernorm.py", line 48, in forward
    return self.rms_forward(x)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 845, in compile_wrapper
    raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 990, in _compile_fx_inner
    raise InductorError(e, currentframe()).with_traceback(
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 974, in _compile_fx_inner
    mb_compiled_graph = fx_codegen_and_compile(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1695, in fx_codegen_and_compile
    return scheme.codegen_and_compile(gm, example_inputs, inputs_to_check, graph_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1505, in codegen_and_compile
    compiled_module = graph.compile_to_module()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2319, in compile_to_module
    return self._compile_to_module()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2329, in _compile_to_module
    mod = self._compile_to_module_lines(wrapper_code)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\graph.py", line 2397, in _compile_to_module_lines
    mod = PyCodeCache.load_by_key_path(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\codecache.py", line 3548, in load_by_key_path
    mod = _reload_python_module(key, path, set_sys_modules=in_toplevel)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\runtime\compile_tasks.py", line 33, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.cache\acestep\torchinductor\5k\c5kgv4bcxjbjmhl6omkc4vjvyiuyzherbjlcveyoczpec5n75yce.py", line 61, in <module>
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\async_compile.py", line 500, in triton
    kernel.precompile(
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 451, in precompile
    self._make_launchers()
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 614, in _make_launchers
    launchers.append(result.make_launcher())
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\runtime\triton_heuristics.py", line 1574, in make_launcher
    self.kernel.load_kernel(device)
  File "C:\Yeni klasör\ACE-Step-1.5-for-windows\.venv\Lib\site-packages\torch\_inductor\runtime\static_cuda_launcher.py", line 130, in load_kernel
    (self.function, self.n_regs, self.n_spills) = _StaticCudaLauncher._load_kernel(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._inductor.exc.InductorError: RuntimeError: CUDA driver error: file not found

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

2026-02-21 20:23:30.269 | WARNING  | acestep.llm_inference:initialize:668 - Falling back to PyTorch backend
2026-02-21 20:23:33.302 | INFO     | acestep.llm_inference:_load_pytorch_model:372 - 5Hz LM initialized successfully using PyTorch backend on cuda
[API Server] LLM model loaded: acestep-5Hz-lm-1.7B
[API Server] All models initialized successfully!
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8001 (Press CTRL+C to quit)
INFO:     127.0.0.1:29249 - "GET /v1/models/list HTTP/1.1" 200 OK
2026-02-21 20:23:54.364 | INFO     | acestep.core.generation.handler.init_service_orchestrator:_reset_lora_state:39 - [_reset_lora_state] LoRA/LoKr state cleared
2026-02-21 20:23:54.421 | INFO     | acestep.core.generation.handler.init_service_loader:_load_main_model_from_checkpoint:55 - [initialize_service] Attempting to load model with attention implementation: flash_attention_2
2026-02-21 20:24:00.795 | INFO     | acestep.core.generation.handler.init_service_loader:_load_main_model_from_checkpoint:79 - [initialize_service] Keeping main model on cuda (persistent)
2026-02-21 20:24:00.825 | INFO     | acestep.core.generation.handler.init_service_orchestrator:switch_dit_model:97 - [switch_dit_model] [OK] Switched to acestep-v15-sft on cuda (attn=flash_attention_2)
INFO:     127.0.0.1:23218 - "POST /v1/models/switch HTTP/1.1" 200 OK
INFO:     127.0.0.1:23218 - "GET /v1/models/list HTTP/1.1" 200 OK
2026-02-21 20:24:20.860 | INFO     | acestep.core.generation.handler.lora.lifecycle:add_lora:220 - VRAM before LoRA load: 7.93GB
2026-02-21 20:24:21.960 | INFO     | acestep.core.generation.handler.lora.lifecycle:add_lora:230 - Base decoder state_dict backed up to CPU (3004.9MB)
2026-02-21 20:24:21.961 | INFO     | acestep.core.generation.handler.lora.lifecycle:add_lora:238 - Loading LoRA adapter from C:\Side-Step-main\lora_output\best as 'best'
2026-02-21 20:24:22.648 | INFO     | acestep.core.generation.handler.lora.lifecycle:add_lora:256 - VRAM after LoRA load: 8.09GB
2026-02-21 20:24:22.671 | INFO     | acestep.core.generation.handler.lora.lifecycle:add_lora:274 - LoRA adapter 'best' loaded from C:\Side-Step-main\lora_output\best (adapters=['best'], targets=264)
INFO:     127.0.0.1:5079 - "POST /v1/lora/load HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "POST /release_task HTTP/1.1" 200 OK
2026-02-21 20:24:58.164 | INFO     | acestep.inference:generate_music:411 - [generate_music] LLM usage decision: thinking=False, use_cot_caption=True, use_cot_language=True, use_cot_metas=True, need_lm_for_cot=True, llm_initialized=True, use_lm=True
2026-02-21 20:24:58.165 | INFO     | acestep.inference:generate_music:469 - LM chunk 1/1 (infer_type=dit) (size: 1, seeds: [1445323623])
2026-02-21 20:24:58.180 | INFO     | acestep.llm_inference:generate_with_stop_condition:1286 - Phase 1: Using user-provided metadata (skipping generation)
2026-02-21 20:24:58.183 | INFO     | acestep.core.generation.handler.generate_music:generate_music:98 - [generate_music] Starting generation...
2026-02-21 20:24:58.185 | INFO     | acestep.core.generation.handler.generate_music:generate_music:101 - [generate_music] Preparing inputs...
2026-02-21 20:24:58.212 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:39 - [_load_model_context] Loading vae to cuda
2026-02-21 20:24:58.427 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:52 - [_load_model_context] Loaded vae to cuda in 0.2143s
2026-02-21 20:24:58.441 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:57 - [_load_model_context] Offloading vae to CPU
2026-02-21 20:24:58.726 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:67 - [_load_model_context] Offloaded vae to CPU in 0.2843s
2026-02-21 20:24:58.737 | INFO     | acestep.core.generation.handler.conditioning_text:_prepare_text_conditioning_inputs:85 -
======================================================================
2026-02-21 20:24:58.739 | INFO     | acestep.core.generation.handler.conditioning_text:_prepare_text_conditioning_inputs:86 - 🔍 [DEBUG] DiT TEXT ENCODER INPUT (Inference)
2026-02-21 20:24:58.742 | INFO     | acestep.core.generation.handler.conditioning_text:_prepare_text_conditioning_inputs:87 - ======================================================================
2026-02-21 20:24:58.742 | INFO     | acestep.core.generation.handler.conditioning_text:_prepare_text_conditioning_inputs:88 - text_prompt:
# Instruction
Fill the audio semantic mask based on the given conditions:

# Caption
A high-octane alternative metal track with an aggressive, percussive energy. The production features a thick wall of sound driven by fast, down-tuned electric guitar riffs and heavy palm-muted chugs. The male vocals are characterized by a rapid, rhythmic staccato delivery in the verses, exploding into a soaring and melodic chorus with powerful layered harmonies. The instrumentation is anchored by relentless, driving drums with complex double-kick patterns and a gritty, syncopated bassline. The atmosphere is intense and confrontational, maintaining a fast tempo and polished studio precision throughout.
Male vocals

# Metas
- bpm: 124
- timesignature: 4/4
- keyscale: D# minor
- duration: 192 seconds
<|endoftext|>

2026-02-21 20:24:58.743 | INFO     | acestep.core.generation.handler.conditioning_text:_prepare_text_conditioning_inputs:89 - ======================================================================
2026-02-21 20:24:58.744 | INFO     | acestep.core.generation.handler.conditioning_text:_prepare_text_conditioning_inputs:90 - lyrics_text:
# Languages
en

# Lyric
[Intro]
Bold motherfucker
Don't you limit your mind

[Verse]
Liberate your mind, you motherfucker
You're so narrow-minded, so narrow-minded
So liberate your mind, motherfucker
Will you liberate your mind?

Liberate your mind, you motherfucker
You're so narrow-minded, so narrow-minded
So liberate your mind now, motherfucker
Will you liberate your mind this time?

[Pre-Chorus]
Bold motherfucker, don't you limit your mind
Can't you see that the pace has just fallen behind?
All the hate in your heart will be leaving you blind
So, bold motherfucker, don't you limit your mind

Now, bold motherfucker, don't you limit your mind
Can't you see that the pace has just fallen behind?
All the hate in your heart will be leaving you blind
So, bold motherfucker, don't you limit your mind this time

[Chorus]
Waiting for your modern messiah
To take away all the hatred
That darkens the light in your eye
Still awaiting I

[Verse]
Liberate your mind, you motherfucker
You're so narrow-minded, so narrow-minded
So liberate your mind, motherfucker
Will you liberate your mind?

Liberate your mind, you motherfucker
You're so narrow-minded, so narrow-minded
So liberate your mind now, motherfucker
Will you liberate your mind this time?

[Pre-Chorus]
Bold motherfucker, don't you limit your mind
Can't you see that the pace has just fallen behind?
All the hate in your heart will be leaving you blind
So, bold motherfucker, don't you limit your mind

Now, bold motherfucker, don't you limit your mind
Can't you see that the pace has just fallen behind?
All the hate in your heart will be leaving you blind
So, bold motherfucker, don't you limit your mind this time

[Chorus]
Waiting for your modern messiah
To take away all the hatred
That darkens the light in your eye
Still awaiting I

[Bridge]
"Out of Zion shall come forth the law
And the word of the Lord from Jerusalem
Nation shall not raise sword against nation
And they shall not learn war anymore
For the mouth of the Lord hath spoken"

[Chorus]
Waiting for your modern messiah
To take away all the hatred
That darkens the light in your eye

How long will we be waiting
For your modern messiah
To take away all the hatred
That darkens the light in your eye?

[Outro]
Still awaiting I
Still awaiting I<|endoftext|>
2026-02-21 20:24:58.745 | INFO     | acestep.core.generation.handler.conditioning_text:_prepare_text_conditioning_inputs:91 - ======================================================================

2026-02-21 20:24:58.758 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:39 - [_load_model_context] Loading vae to cuda
2026-02-21 20:24:58.970 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:52 - [_load_model_context] Loaded vae to cuda in 0.2102s
2026-02-21 20:24:58.986 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:57 - [_load_model_context] Offloading vae to CPU
2026-02-21 20:24:59.201 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:67 - [_load_model_context] Offloaded vae to CPU in 0.2152s
2026-02-21 20:24:59.202 | INFO     | acestep.core.generation.handler.conditioning_embed:preprocess_batch:110 - [preprocess_batch] Inferring prompt embeddings...
2026-02-21 20:24:59.206 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:39 - [_load_model_context] Loading text_encoder to cuda
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.
2026-02-21 20:24:59.541 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:52 - [_load_model_context] Loaded text_encoder to cuda in 0.3343s
2026-02-21 20:24:59.953 | INFO     | acestep.core.generation.handler.conditioning_embed:preprocess_batch:113 - [preprocess_batch] Inferring lyric embeddings...
2026-02-21 20:24:59.953 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:57 - [_load_model_context] Offloading text_encoder to CPU
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
2026-02-21 20:25:00.468 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:67 - [_load_model_context] Offloaded text_encoder to CPU in 0.5128s
2026-02-21 20:25:00.468 | INFO     | acestep.core.generation.handler.service_generate_execute:_execute_service_generate_diffusion:129 - [service_generate] Generating audio... (DiT backend: PyTorch (cuda))
2026-02-21 20:25:00.469 | INFO     | acestep.core.generation.handler.service_generate_execute:_execute_service_generate_diffusion:130 - [service_generate] DiT diffusion via PyTorch (cuda)... solver=ode, guidance=apg, steps=20, cfg_scale=9.0, seed=[1445323623], shift=1.0, cfg_interval=[0.0, 1.0], cover_strength=1.0
2026-02-21 20:25:00.763 | INFO     | acestep.core.generation.handler.service_generate_execute:_execute_service_generate_diffusion:213 - [service_generate] DiT diffusion via PyTorch (cuda)...
 10%|#################1                                                                                                                                                         | 2/20 [00:01<00:13,  1.37steps/s]INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
 20%|##################################2                                                                                                                                        | 4/20 [00:02<00:10,  1.52steps/s]INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
 40%|####################################################################4                                                                                                      | 8/20 [00:05<00:07,  1.58steps/s]INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
 55%|#############################################################################################5                                                                            | 11/20 [00:07<00:05,  1.59steps/s]INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
 75%|###############################################################################################################################5                                          | 15/20 [00:09<00:03,  1.60steps/s]INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
 85%|################################################################################################################################################5                         | 17/20 [00:10<00:01,  1.60steps/s]INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
100%|##########################################################################################################################################################################| 20/20 [00:12<00:00,  1.57steps/s]
2026-02-21 20:25:13.603 | INFO     | acestep.core.generation.handler.generate_music_decode:_prepare_generate_music_decode_state:41 - [generate_music] Model generation completed. Decoding latents...
2026-02-21 20:25:13.606 | DEBUG    | acestep.core.generation.handler.generate_music_decode:_prepare_generate_music_decode_state:63 - [generate_music] pred_latents: torch.Size([1, 4800, 64]), dtype=torch.bfloat16
2026-02-21 20:25:13.606 | DEBUG    | acestep.core.generation.handler.generate_music_decode:_prepare_generate_music_decode_state:64 - [generate_music] time_costs: {'encoder_time_cost': 0.06706714630126953, 'diffusion_time_cost': 12.772854804992676, 'diffusion_per_step_time_cost': 0.6386427402496337, 'total_time_cost': 12.839921951293945, 'offload_time_cost': 1.7711918354034424}
2026-02-21 20:25:13.612 | INFO     | acestep.core.generation.handler.generate_music_decode:_decode_generate_music_pred_latents:118 - [generate_music] Decoding latents with VAE...
2026-02-21 20:25:13.612 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:39 - [_load_model_context] Loading vae to cuda
2026-02-21 20:25:13.779 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:52 - [_load_model_context] Loaded vae to cuda in 0.1662s
2026-02-21 20:25:13.784 | DEBUG    | acestep.core.generation.handler.generate_music_decode:_decode_generate_music_pred_latents:127 - [generate_music] Before VAE decode: allocated=8.43GB, max=11.39GB
2026-02-21 20:25:13.784 | INFO     | acestep.core.generation.handler.generate_music_decode:_decode_generate_music_pred_latents:145 - [generate_music] Effective free VRAM before VAE decode: 6.15 GB
2026-02-21 20:25:13.784 | INFO     | acestep.core.generation.handler.generate_music_decode:_decode_generate_music_pred_latents:163 - [generate_music] Using tiled VAE decode to reduce VRAM usage...
2026-02-21 20:25:13.784 | DEBUG    | acestep.core.generation.handler.memory_utils:_get_auto_decode_chunk_size:75 - [_get_auto_decode_chunk_size] Effective free VRAM: 6.15 GB
2026-02-21 20:25:13.785 | DEBUG    | acestep.core.generation.handler.memory_utils:_should_offload_wav_to_cpu:98 - [_should_offload_wav_to_cpu] Effective free VRAM: 6.15 GB
2026-02-21 20:25:13.785 | INFO     | acestep.core.generation.handler.vae_decode:tiled_decode:56 - [tiled_decode] chunk_size=128, offload_wav_to_cpu=True, latents_shape=torch.Size([1, 64, 4800])
2026-02-21 20:25:13.786 | WARNING  | acestep.core.generation.handler.vae_decode_chunks:_tiled_decode_inner:35 - [tiled_decode] Reduced overlap from 64 to 32 for chunk_size=128
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
2026-02-21 20:25:18.126 | DEBUG    | acestep.core.generation.handler.generate_music_decode:_decode_generate_music_pred_latents:185 - [generate_music] After VAE decode: allocated=8.58GB, max=11.39GB
2026-02-21 20:25:18.154 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:57 - [_load_model_context] Offloading vae to CPU
2026-02-21 20:25:18.400 | INFO     | acestep.core.generation.handler.init_service_offload_context:_load_model_context:67 - [_load_model_context] Offloaded vae to CPU in 0.2448s
2026-02-21 20:25:18.400 | INFO     | acestep.core.generation.handler.generate_music_payload:_build_generate_music_success_payload:35 - [generate_music] VAE decode completed. Preparing audio tensors...
2026-02-21 20:25:18.402 | INFO     | acestep.core.generation.handler.generate_music_payload:_build_generate_music_success_payload:45 - [generate_music] Done! Generated 1 audio tensors.
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
2026-02-21 20:25:18.736 | INFO     | acestep.inference:generate_music:689 - [Normalization] Audio 0 BEFORE: Peak=1.0000, Target=-1.0dB
2026-02-21 20:25:18.771 | INFO     | acestep.inference:generate_music:694 - [Normalization] Audio 0 AFTER: Peak=0.8913
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
2026-02-21 20:25:31.201 | DEBUG    | acestep.audio_utils:save_audio:207 - [AudioSaver] Fallback soundfile Saved audio to C:\Users\baran\AppData\Local\Temp\acestep_audio\86dacffd-b6a3-94ca-43ce-0635a3a5aba6.mp3 (mp3, 48000Hz)
INFO:     127.0.0.1:21427 - "POST /query_result HTTP/1.1" 200 OK
INFO:     127.0.0.1:37300 - "GET /v1/audio?path=C%3A%5CUsers%5Cbaran%5CAppData%5CLocal%5CTemp%5Cacestep_audio%5C86dacffd-b6a3-94ca-43ce-0635a3a5aba6.mp3 HTTP/1.1" 200 OK
INFO:     127.0.0.1:21427 - "GET /v1/models/list HTTP/1.1" 200 OK

**other terminal:**

> ace-step-ui-server@1.0.0 dev
> tsx watch src/index.ts

Running SQLite database migrations...
Migrations completed successfully!
Column model already exists in songs table
ACE-Step UI Server running on http://localhost:3001
Environment: development
ACE-Step API: http://localhost:8001
LAN access: http://192.168.0.10:3001
LAN access: http://172.30.176.28:3001
Models proxy: ACE-Step backend not reachable yet
Models proxy: ACE-Step backend not reachable yet
Initializing local storage provider
Models proxy: ACE-Step backend not reachable yet
Models proxy: ACE-Step backend not reachable yet
Models proxy: ACE-Step backend not reachable yet
Models proxy: ACE-Step backend not reachable yet
Models proxy: ACE-Step backend not reachable yet
Models proxy: ACE-Step backend not reachable yet
Models proxy: ACE-Step backend not reachable yet
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.5488005819910705, \"stage\": \"Generating music (batch size: 1)...\"}]",
  "status": 0,
  "progress_text": "20:24:59 | INFO | [_load_model_context] Offloading text_encoder to CPU"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.5969274877260211, \"stage\": \"Generating music (batch size: 1)...\"}]",
  "status": 0,
  "progress_text": "10%|#################1                                                                                                                                                         | 2/20 [00:01<00:13,  1.37steps/s]"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.6256518085072434, \"stage\": \"Generating music (batch size: 1)...\"}]",
  "status": 0,
  "progress_text": "20%|##################################2                                                                                                                                        | 4/20 [00:02<00:10,  1.52steps/s]"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.673334664253243, \"stage\": \"Generating music (batch size: 1)...\"}]",
  "status": 0,
  "progress_text": "40%|####################################################################4                                                                                                      | 8/20 [00:05<00:07,  1.58steps/s]"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.7020856543649756, \"stage\": \"Generating music (batch size: 1)...\"}]",
  "status": 0,
  "progress_text": "55%|#############################################################################################5                                                                            | 11/20 [00:07<00:05,  1.59steps/s]"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.7497285264046412, \"stage\": \"Generating music (batch size: 1)...\"}]",
  "status": 0,
  "progress_text": "75%|###############################################################################################################################5                                          | 15/20 [00:09<00:03,  1.60steps/s]"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.7783268903951385, \"stage\": \"Generating music (batch size: 1)...\"}]",
  "status": 0,
  "progress_text": "85%|################################################################################################################################################5                         | 17/20 [00:10<00:01,  1.60steps/s]"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.8, \"stage\": \"Decoding audio...\"}]",
  "status": 0,
  "progress_text": "20:25:13 | WARNING | [tiled_decode] Reduced overlap from 64 to 32 for chunk_size=128"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.8, \"stage\": \"Decoding audio...\"}]",
  "status": 0,
  "progress_text": "20:25:13 | WARNING | [tiled_decode] Reduced overlap from 64 to 32 for chunk_size=128"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.99, \"stage\": \"Preparing audio data...\"}]",
  "status": 0,
  "progress_text": "20:25:18 | INFO | [generate_music] Done! Generated 1 audio tensors."
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.99, \"stage\": \"Preparing audio data...\"}]",
  "status": 0,
  "progress_text": "20:25:18 | INFO | [Normalization] Audio 0 AFTER: Peak=0.8913"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.99, \"stage\": \"Preparing audio data...\"}]",
  "status": 0,
  "progress_text": "20:25:18 | INFO | [Normalization] Audio 0 AFTER: Peak=0.8913"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.99, \"stage\": \"Preparing audio data...\"}]",
  "status": 0,
  "progress_text": "20:25:18 | INFO | [Normalization] Audio 0 AFTER: Peak=0.8913"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.99, \"stage\": \"Preparing audio data...\"}]",
  "status": 0,
  "progress_text": "20:25:18 | INFO | [Normalization] Audio 0 AFTER: Peak=0.8913"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.99, \"stage\": \"Preparing audio data...\"}]",
  "status": 0,
  "progress_text": "20:25:18 | INFO | [Normalization] Audio 0 AFTER: Peak=0.8913"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"\", \"wave\": \"\", \"status\": 0, \"create_time\": 1771694698, \"env\": \"development\", \"progress\": 0.99, \"stage\": \"Preparing audio data...\"}]",
  "status": 0,
  "progress_text": "20:25:18 | INFO | [Normalization] Audio 0 AFTER: Peak=0.8913"
}
Task data: {
  "task_id": "9e2dd5a8-cb92-4bc7-b997-47dd3144d7aa",
  "result": "[{\"file\": \"/v1/audio?path=C%3A%5CUsers%5Cbaran%5CAppData%5CLocal%5CTemp%5Cacestep_audio%5C86dacffd-b6a3-94ca-43ce-0635a3a5aba6.mp3\", \"wave\": \"\", \"status\": 1, \"create_time\": 1771694698, \"env\": \"development\", \"prompt\": \"A high-octane alternative metal track with an aggressive, percussive energy. The production features a thick wall of sound driven by fast, down-tuned electric guitar riffs and heavy palm-muted chugs. The male vocals are characterized by a rapid, rhythmic staccato delivery in the verses, exploding into a soaring and melodic chorus with powerful layered harmonies. The instrumentation is anchored by relentless, driving drums with complex double-kick patterns and a gritty, syncopated bassline. The atmosphere is intense and confrontational, maintaining a fast tempo and polished studio precision throughout.\\nMale vocals\\nMale vocals\", \"lyrics\": \"[Intro]\\nBold motherfucker\\nDon't you limit your mind\\n\\n[Verse]\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind, motherfucker\\nWill you liberate your mind?\\n\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind now, motherfucker\\nWill you liberate your mind this time?\\n\\n[Pre-Chorus]\\nBold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind\\n\\nNow, bold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind this time\\n[Chorus]\\nWaiting for your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye\\nStill awaiting I\\n\\n[Verse]\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind, motherfucker\\nWill you liberate your mind?\\n\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind now, motherfucker\\nWill you liberate your mind this time?\\n\\n[Pre-Chorus]\\nBold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind\\n\\nNow, bold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind this time\\n[Chorus]\\nWaiting for your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye\\nStill awaiting I\\n\\n[Bridge]\\n\\\"Out of Zion shall come forth the law\\nAnd the word of the Lord from Jerusalem\\nNation shall not raise sword against nation\\nAnd they shall not learn war anymore\\nFor the mouth of the Lord hath spoken\\\"\\n\\n[Chorus]\\nWaiting for your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye\\n\\nHow long will we be waiting\\nFor your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye?\\n\\n[Outro]\\nStill awaiting I\\nStill awaiting I\", \"metas\": {\"bpm\": 124, \"duration\": 192.0, \"genres\": \"N/A\", \"keyscale\": \"D# minor\", \"timesignature\": \"4/4\", \"prompt\": \"A high-octane alternative metal track with an aggressive, percussive energy. The production features a thick wall of sound driven by fast, down-tuned electric guitar riffs and heavy palm-muted chugs. The male vocals are characterized by a rapid, rhythmic staccato delivery in the verses, exploding into a soaring and melodic chorus with powerful layered harmonies. The instrumentation is anchored by relentless, driving drums with complex double-kick patterns and a gritty, syncopated bassline. The atmosphere is intense and confrontational, maintaining a fast tempo and polished studio precision throughout.\\nMale vocals\\nMale vocals\", \"lyrics\": \"[Intro]\\nBold motherfucker\\nDon't you limit your mind\\n\\n[Verse]\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind, motherfucker\\nWill you liberate your mind?\\n\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind now, motherfucker\\nWill you liberate your mind this time?\\n\\n[Pre-Chorus]\\nBold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind\\n\\nNow, bold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind this time\\n[Chorus]\\nWaiting for your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye\\nStill awaiting I\\n\\n[Verse]\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind, motherfucker\\nWill you liberate your mind?\\n\\nLiberate your mind, you motherfucker\\nYou're so narrow-minded, so narrow-minded\\nSo liberate your mind now, motherfucker\\nWill you liberate your mind this time?\\n\\n[Pre-Chorus]\\nBold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind\\n\\nNow, bold motherfucker, don't you limit your mind\\nCan't you see that the pace has just fallen behind?\\nAll the hate in your heart will be leaving you blind\\nSo, bold motherfucker, don't you limit your mind this time\\n[Chorus]\\nWaiting for your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye\\nStill awaiting I\\n\\n[Bridge]\\n\\\"Out of Zion shall come forth the law\\nAnd the word of the Lord from Jerusalem\\nNation shall not raise sword against nation\\nAnd they shall not learn war anymore\\nFor the mouth of the Lord hath spoken\\\"\\n\\n[Chorus]\\nWaiting for your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye\\n\\nHow long will we be waiting\\nFor your modern messiah\\nTo take away all the hatred\\nThat darkens the light in your eye?\\n\\n[Outro]\\nStill awaiting I\\nStill awaiting I\"}, \"generation_info\": \"**🎵 Total generation time (1 song): 17.63s**\\n- 17.63s per song\\n- DiT phase (1 song): 17.63s\", \"seed_value\": \"1445323623\", \"lm_model\": \"acestep-5Hz-lm-0.6B\", \"dit_model\": \"acestep-v15-sft\", \"progress\": 1.0, \"stage\": \"succeeded\"}]",
  "status": 1,
  "progress_text": "20:25:31 | DEBUG | [AudioSaver] Fallback soundfile Saved audio to C:\\Users\\baran\\AppData\\Local\\Temp\\acestep_audio\\86dacffd-b6a3-94ca-43ce-0635a3a5aba6.mp3 (mp3, 48000Hz)"
}
[Batch 1/1] Original file path: /v1/audio?path=C%3A%5CUsers%5Cbaran%5CAppData%5CLocal%5CTemp%5Cacestep_audio%5C86dacffd-b6a3-94ca-43ce-0635a3a5aba6.mp3
[Batch 1] Prepended domain to API path: http://localhost:8001/v1/audio?path=C%3A%5CUsers%5Cbaran%5CAppData%5CLocal%5CTemp%5Cacestep_audio%5C86dacffd-b6a3-94ca-43ce-0635a3a5aba6.mp3

**Comment by scragnog** [comment]
Fixed in feature/model-loading-enhancements (merged to qinglong). The root cause was that _ensure_llm_ready() never compared the requested LM model against the loaded one — it returned immediately if any LLM was initialized. Now implements hot-switching: detects model mismatch, unloads old, and loads new.
